steps:
- task: NodeTool@0
  displayName: 'Use Node 16.x'
  inputs:
    versionSpec: 16.x

- task: Npm@1
  inputs:
    command: custom
    customCommand: ci --no-optional
  displayName: 'Install Dependencies'
